# This workflow will run when a PR is opened against the `main` branch.
#
# It will trigger the reusable workflows:
#   `.github/workflows/mypy.yml` - which runs mypy on the repository.
#
name: Tests for PRs to main

on:
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  mypy:
    uses: ./.github/workflows/mypy.yml
